version: '3.8'
services:
  mysql:
     image: mysql:9.1
     container_name: mysql
     ports: 
       - 3306:3306
     environment:
        MYSQL_ROOT_PASSWORD: root
     volumes:
      - ./sqls:/docker-entrypoint-initdb.d
  adminer:
     image: adminer:4.8.1
     container_name: adminer
     ports:
       - 8080:8080
  redis:
     image: redis:7.4.1
     container_name: redis
     ports:
       - 6379:6379
  rcli:
    image: redis:7.4.1
    container_name: rcli
    links:
       - redis
    command: redis-cli -h redis
  redis-commander:
     image: rediscommander/redis-commander:latest
     container_name: redis-commander
     ports:
       - "8081:8081"
     environment:
       - REDIS_HOSTS=local:redis:6379
